services:
  app_todo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_todo
    restart: always
    command: >
      sh -c "npx prisma db push && npm run start"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db_todo
    networks:
      - npm_network

  db_todo:
    image: postgres:13-alpine
    container_name: db_todo
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: Rahasia123
      POSTGRES_DB: db_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - npm_network

volumes:
  postgres_data:

networks:
  npm_network:
    external: true