services:
  app_todo:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_todo
    container_name: app_todo
    restart: always
    command: >
      sh -c "npx prisma db push && npm run start"
    env_file:
      - .env
    depends_on:
      - db_todo
    networks:
      - npm_networks

  app_todo_debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    image: app_todo_debian
    container_name: app_todo_debian
    restart: always
    command: >
      sh -c "npx prisma db push && npm run start"
    env_file:
      - .env
    depends_on:
      - db_todo
    networks:
      - npm_networks

  app_todo_alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: app_todo_alpine
    container_name: app_todo_alpine
    restart: always
    command: >
      sh -c "npx prisma db push && npm run start"
    env_file:
      - .env
    depends_on:
      - db_todo
    networks:
      - npm_networks

  app_todo_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: app_todo_ubuntu
    container_name: app_todo_ubuntu
    restart: always
    command: >
      sh -c "npx prisma db push && npm run start"
    env_file:
      - .env
    depends_on:
      - db_todo
    networks:
      - npm_networks

  db_todo:
    image: postgres:13-alpine
    container_name: db_todo
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: Rahasia123
      POSTGRES_DB: db_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - npm_networks

volumes:
  postgres_data:

networks:
  npm_networks:
    # external: true