name: Deploy to VPS

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Deploy with Docker Compose via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  port: ${{ secrets.VPS_PORT }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/dean-cloud/github/todolist-expressjs
                      # Pull latest changes 
                      git pull origin main
                      # Rebuild images and restart containers
                      docker compose up -d --build
